set_languages("c++latest")
add_requires("ftxui")
add_packages("boost", {asio = true, system = true})
package("stdexec-git")
  add_deps("cmake")
  set_sourcedir(path.join(os.scriptdir(), "ThirdParty/stdexec"))
  on_install(function (package)
      local configs = {}
      import("package.tools.cmake").install(package, configs)
  end)
  on_test(function (package)
      assert(package:has_cfuncs("add", {includes = "asioexec/use_senders.hpp"}))
  end)
package_end()
add_requires("stdexec-git")

target("Client")
  add_files("src/main.cpp", "src/**/*.cpp")
  add_packages("boost", "ftxui", "stdexec")
  -- add_includedirs("./ThirdParty/stdexec/include/")
